---
  dataSource: "prs"
  onlyMilestones: false
  changelogFilename: "CHANGELOG.md"
  ignoreIssuesWith:
    - "help wanted"
  ignoreLabels:
    - "tags/releases"
    - "duplicate"
    - "wontfix"
    - "invalid"
  groupBy:
    New features:
      - "feature"
    Bug Fixes:
      - "bug"
    Enhancements:
      - "enhancement"
    Documentation:
      - "documentation"
    Internal:
      - "internal"