from typing import TypeVar

T = TypeVar("T")

JSON_EXTENSIONS = [".json"]
YAML_EXTENSIONS = [".yaml", ".yml"]
MAX_TTY_LENGTH = 180
NOT_AVAILABLE = "N/A"
# CLI OPTIONS
CLI_CONFIGURATION_OPTION = "--configuration"
CLI_CONFIGURATION_OPTION_DEFAULT_VALUE = ".bmycconfig.json"
CLI_CONFIGURATION_SHORT_OPTION = "-c"
CLI_FORCE_OPTION = "--force"
CLI_FORCE_SHORT_OPTION = "-f"
CLI_GITHUB_TOKEN_OPTION = "--github-token"
CLI_GITHUB_TOKEN_ENV_VAR_KEY = "BMYC_GITHUB_TOKEN"
CLI_INSECURE_OPTION = "--insecure"
CLI_INSECURE_SHORT_OPTION = "-i"
CLI_SUMMARY_OPTION = "--summary"
CLI_SUMMARY_OPTION_DEFAULT_VALUE = "bmyc-summary.md"
CLI_SUMMARY_SHORT_OPTION = "-s"
