name: Tags
on:
  release:
    types: [created]
jobs:
  Publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      CHANGELOG_FILE: CHANGELOG.md
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'main'
          submodules: recursive
          fetch-depth: 1
      - name: Publish on Npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}